alter table public.bebrave_visitors add column if not exists epic_pity integer not null default 0 check (epic_pity between 0 and 8);
do $$ declare job record; begin for job in select jobid from cron.job where jobname='bebrave-hourly-growth' loop perform cron.unschedule(job.jobid); end loop; end $$;
drop function if exists public.bebrave_process_hourly_growth();
create or replace function private.bebrave_finalize_one(p_session uuid) returns text language plpgsql set search_path='' as $function$
declare s public.bebrave_sessions; seq bigint; finished timestamptz;
begin select * into s from public.bebrave_sessions where id=p_session for update; if not found then return 'missing'; end if; if s.status in ('completed','empty','cancelled') then return s.status; end if; if s.status<>'drawing' or s.drawing_deadline is null or s.drawing_deadline>clock_timestamp() then return s.status; end if; finished:=s.drawing_deadline;
if s.point_count>0 then perform pg_advisory_xact_lock(731001); update public.bebrave_tree_state set completed_count=completed_count+1,height=height+288,active_top=active_top+288,active_bottom=active_bottom+288,pending_growth_carvings=0,revision=revision+1,updated_at=now() where id=true returning completed_count into seq; update public.bebrave_sessions set status='completed',drawing_finished_at=finished,public_sequence=seq,updated_at=now() where id=s.id; update public.bebrave_visitors set last_carved_at=finished,last_seen_at=now(),epic_pity=case when s.chosen_rarity='epic' then 0 else least(epic_pity+1,8) end where id=s.visitor_id; else update public.bebrave_sessions set status='empty',drawing_finished_at=finished,updated_at=now() where id=s.id; update public.bebrave_visitors set last_seen_at=now() where id=s.visitor_id; end if; return case when s.point_count>0 then 'completed' else 'empty' end; end; $function$;
create or replace function public.bebrave_finish_session(p_session uuid,p_visitor_hash text) returns text language plpgsql set search_path='' as $function$
declare v uuid; s public.bebrave_sessions; begin select id into v from public.bebrave_visitors where visitor_hash=p_visitor_hash; select * into s from public.bebrave_sessions where id=p_session and visitor_id=v for update; if not found then raise exception 'session not owned'; end if; if s.status in ('completed','empty') then return s.status; end if; if s.status<>'drawing' or s.drawing_deadline is null then raise exception 'session not drawing'; end if; if clock_timestamp()<s.drawing_deadline then update public.bebrave_sessions set drawing_deadline=clock_timestamp(),updated_at=now() where id=s.id; end if; return private.bebrave_finalize_one(s.id); end; $function$;
revoke execute on function public.bebrave_finish_session(uuid,text) from public,anon,authenticated; grant execute on function public.bebrave_finish_session(uuid,text) to service_role;
