import {existsSync} from "node:fs";
import {resolve} from "node:path";

export const artworkThemes={
  "living-light":":root",
  "living-dark":'html[data-theme="dark"]',
  "felled-light":'html[data-timeline="felled"]',
  "felled-dark":'html[data-timeline="felled"][data-theme="dark"]',
};
export function validateArtwork(assets,publicPath){
  for(const [slot,asset] of Object.entries(assets)){
    if(!/^[a-z][a-z0-9-]*$/.test(slot)||!['native','image','mask','none'].includes(asset.kind))throw Error(`Invalid artwork slot: ${slot}`);
    if(['image','mask'].includes(asset.kind)&&!asset.src)throw Error(`Missing artwork source: ${slot}`);
    if(asset.variants&&Object.keys(asset.variants).some(theme=>!Object.hasOwn(artworkThemes,theme)))throw Error(`Invalid artwork theme: ${slot}`);
    for(const [property,values] of Object.entries({fit:['contain','cover'],tint:['ink','accent','foliage','brass','sun'],material:['glass','paper','none']})){
      if(asset[property]!==undefined&&!values.includes(asset[property]))throw Error(`Invalid artwork ${property}: ${slot}`);
    }
    for(const source of [asset.src,...Object.values(asset.variants??{})].filter(Boolean)){
      if(!/^\/images\/[A-Za-z0-9_/-]+\.(?:svg|png|jpe?g|webp|avif)$/.test(source)||source.includes('..')||source.includes('//'))throw Error(`Invalid artwork path: ${slot}`);
      if(publicPath&&!existsSync(resolve(publicPath,source.slice(1))))throw Error(`Artwork file is missing: ${slot}`);
    }
  }
}
export function artworkCSS(assets){
  validateArtwork(assets);
  return '/* Generated by scripts/build-art-assets.mjs. Edit design/art-assets.json. */\n'+
    Object.entries(artworkThemes).map(([theme,selector])=>`${selector} {\n${Object.entries(assets).map(([slot,asset])=>{
      const source=asset.kind==='none'?undefined:asset.variants?.[theme]??asset.src;
      return `  --asset-${slot}: ${source?`url("${source}")`:'none'};`;
    }).join('\n')}\n}`).join('\n\n')+'\n';
}
